apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi-hello.fullname" . }}-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "fastapi-hello.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
