apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-hello-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/markjvaz99/portfolio.git"
    targetRevision: HEAD
    path: "charts/fastapi-hello"
    helm:
      valueFiles: []
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
